export const ErrorCodes = {
  // auth
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',

  // validation / request
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED', // ✅ NUEVO

  // users/roles (ejemplos)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_PROTECTED: 'ROLE_PROTECTED',

  // tenancy
  TENANT_REQUIRED: 'TENANT_REQUIRED',

  // generic
  INTERNAL: 'INTERNAL',

  // pasturas
  PASTURA_NOT_FOUND: 'PASTURA_NOT_FOUND',
  PASTURA_DUPLICATE_NOMBRE: 'PASTURA_DUPLICATE_NOMBRE',
  PASTURA_PRECIO_INVALID: 'PASTURA_PRECIO_INVALID',

  // establecimientos
  ESTABLECIMIENTO_NOT_FOUND: 'ESTABLECIMIENTO_NOT_FOUND',
  ESTABLECIMIENTO_DUPLICATE_NOMBRE: 'ESTABLECIMIENTO_DUPLICATE_NOMBRE',
  ESTABLECIMIENTO_HAS_LOTES: 'ESTABLECIMIENTO_HAS_LOTES',

  // lotes
  LOTE_NOT_FOUND: 'LOTE_NOT_FOUND',
  LOTE_DUPLICATE_NOMBRE: 'LOTE_DUPLICATE_NOMBRE',

  // proveedores
  PROVEEDOR_NOT_FOUND: 'PROVEEDOR_NOT_FOUND',
  PROVEEDOR_DUPLICATE: 'PROVEEDOR_DUPLICATE',
  PROVEEDOR_DUPLICATE_NOMBRE: 'PROVEEDOR_DUPLICATE_NOMBRE',
  PROVEEDOR_DUPLICATE_CUIT: 'PROVEEDOR_DUPLICATE_CUIT',
  PROVEEDOR_CUIT_INVALID: 'PROVEEDOR_CUIT_INVALID',
  PROVEEDOR_TIPO_INVALID: 'PROVEEDOR_TIPO_INVALID',

  // centro de costo
  CENTRO_COSTO_NOT_FOUND: 'CENTRO_COSTO_NOT_FOUND',
  CENTRO_COSTO_DUPLICATE: 'CENTRO_COSTO_DUPLICATE',
  CENTRO_COSTO_NOMBRE_INMUTABLE: 'CENTRO_COSTO_NOMBRE_INMUTABLE',
  CENTRO_COSTO_DELETE_FORBIDDEN: 'CENTRO_COSTO_DELETE_FORBIDDEN',
  CENTRO_COSTO_RESTORE_NOT_APPLICABLE: 'CENTRO_COSTO_RESTORE_NOT_APPLICABLE',

  // categorías
  CATEGORIA_NOT_FOUND: 'CATEGORIA_NOT_FOUND',
  CATEGORIA_DUPLICATE: 'CATEGORIA_DUPLICATE',

  // gastos
  MONEY_INVALID: 'MONEY_INVALID',

  GASTO_LOTE_NOT_FOUND: 'GASTO_LOTE_NOT_FOUND',
  GASTO_TROPA_NOT_FOUND: 'GASTO_TROPA_NOT_FOUND',

  // tropas
  TROPA_NOT_FOUND: 'TROPA_NOT_FOUND',
  TROPA_DUPLICATE_CODIGO: 'TROPA_DUPLICATE_CODIGO',
  TROPA_INVALID: 'TROPA_INVALID',
  TROPA_CERRADA_NO_EDITABLE: 'TROPA_CERRADA_NO_EDITABLE',

  // ocupaciones
  OCUPACION_NOT_FOUND: 'OCUPACION_NOT_FOUND',
  OCUPACION_TROPAS_REQUIRED: 'OCUPACION_TROPAS_REQUIRED',
  OCUPACION_PESO_INICIO_REQUIRED: 'OCUPACION_PESO_INICIO_REQUIRED',
  OCUPACION_PESO_FIN_REQUIRED: 'OCUPACION_PESO_FIN_REQUIRED',
  OCUPACION_CABEZAS_INVALID: 'OCUPACION_CABEZAS_INVALID',
  OCUPACION_FECHAS_INVALID: 'OCUPACION_FECHAS_INVALID',
  OCUPACION_NOT_OPEN: 'OCUPACION_NOT_OPEN',
  OCUPACION_DUPLICATE_OPEN_LOTE: 'OCUPACION_DUPLICATE_OPEN_LOTE',

  LOTE_NO_DISPONIBLE: 'LOTE_NO_DISPONIBLE',

  EVENTO_MUERTE_NOT_FOUND: 'EVENTO_MUERTE_NOT_FOUND',
  EVENTO_MUERTE_INVALID: 'EVENTO_MUERTE_INVALID',

  TROPA_CERRADA_NO_EVENTOS: 'TROPA_CERRADA_NO_EVENTOS',
  TROPA_CABEZAS_INSUFICIENTES: 'TROPA_CABEZAS_INSUFICIENTES',

  DIVISION_TROPA_NOT_FOUND: 'DIVISION_TROPA_NOT_FOUND',
  DIVISION_TROPA_INVALID: 'DIVISION_TROPA_INVALID',

  TROPA_CERRADA_NO_DIVIDIR: 'TROPA_CERRADA_NO_DIVIDIR',

  TROPA_DESTINO_DUPLICATE_CODIGO: 'TROPA_DESTINO_DUPLICATE_CODIGO',

  // movimientos
  TIPO_CAMBIO_INVALID: 'TIPO_CAMBIO_INVALID',
  OCUPACION_FECHA_HASTA_REQUIRED: 'OCUPACION_FECHA_HASTA_REQUIRED',
  OCUPACION_PASTURA_SNAPSHOT_REQUIRED: 'OCUPACION_PASTURA_SNAPSHOT_REQUIRED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
